### ISSUE TITLE
cdata blocks?

### ISSUE THREAD

**Issue by nturley** [drom/onml#6]
I was having some trouble with SVG style tags. It looks like for internal CSS [it's recommended](https://www.w3.org/TR/SVG/styling.html#StylingWithCSS) to wrap it in a CDATA tag to avoid it being parsed like XML
```XML
<style type="text/css"><![CDATA[
rect {
  fill: red;
  stroke: blue;
  stroke-width: 3
}
]]></style>
```
I expected it to produce this:
```
[ 'style', { type: 'text/css' }, '<![CDATA[
rect {
  fill: red;
  stroke: blue;
  stroke-width: 3
}
]]>' ]
```
instead, it produced this:
```
[ 'style', { type: 'text/css' } ]
```
Is this expected? Does JsonML not support CDATA?

**Comment by drom** [comment]
@nturley thank you for reporting. I have never used CDATA with onml before.
